import { NextResponse } from 'next/server';

/**
 * API to initiate the transition from Pilot to Premium Subscription
 * Sets a 21-day trial period to match the Pilot MOU.
 */

const STRIPE_PRICE_ID = 'price_1TQmkzCoI11C1SjQS1Wnx23d';

export async function POST(request: Request) {
  try {
    const { firmName, email, zipCode } = await request.json();

    console.log(`[BILLING] Initiating subscription transition for ${firmName} (${zipCode})`);

    // In a real implementation, we would use the Stripe Node SDK:
    // const session = await stripe.checkout.sessions.create({
    //   customer_email: email,
    //   line_items: [{ price: STRIPE_PRICE_ID, quantity: 1 }],
    //   mode: 'subscription',
    //   subscription_data: { trial_period_days: 21 },
    //   success_url: `${process.env.NEXT_PUBLIC_URL}/dashboard?zip=${zipCode}&payment=success`,
    //   cancel_url: `${process.env.NEXT_PUBLIC_URL}/dashboard?zip=${zipCode}&payment=cancel`,
    // });

    // For this MVP, we simulate the success of the link generation
    return NextResponse.json({
      success: true,
      checkoutUrl: 'https://buy.stripe.com/test_8x26oGcDCaLM65mfIv1ZS2q', // The link generated by create_stripe_product
      trialEndDate: '2026-05-18',
      message: `La transition pour ${firmName} est configurée. Le prélèvement de 897€ HT débutera le 18 mai 2026.`
    });
  } catch (error) {
    console.error('Subscription error:', error);
    return NextResponse.json({ error: 'Failed to initiate billing transition' }, { status: 500 });
  }
}
